[package]
name = "morgul"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.1", features = ["derive"] }
clap = { version = "4.5.41", features = ["derive"] }
pnet = { version = "0.35.0", default-features = false, features = ["pnet_datalink", "std"] }
